name: Kanboard

on:
  push:
    branches:
      - master

jobs:
  kanboard:
    uses: moogur/all-workflows/.github/workflows/kanboard.yml@master
    secrets: inherit
    with:
      kanboard_columns: "69,70,71,72,73"
      project_type: "single_branch"
      event_type: "push"
